example:
  property: OrganizationAmbienteDefault

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/eagle_eye_local
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver