spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/eagle_eye_local?useSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver